import assert from 'node:assert/strict';
import { sim, launchSim } from '../js/sim/sim.js';
import { makePilot } from '../js/flight/pilot.js';
import { mission, EXEC, startMission, stopMission, tickMission } from '../js/mission/run.js';
import { makeMission, makeStep } from '../js/mission/script.js';
import { AP_POWER, autopilot } from '../js/flight/autopilot.js';
import { batteryCap } from '../js/flight/ship.js';
import { stations } from '../js/station/stations.js';
import { contacts } from '../js/flight/turrets.js';
import { planJob, beginAriaWatch, shouldBreakOff } from '../js/aria/pilot.js';
import { hullMaxOf } from '../js/flight/repair.js';
import { ariaMind } from '../js/aria/mind.js';
makePilot('Miner','terran','mining',null); launchSim('MiningLoop','sol');
const ship = sim.ship; ship.hold = {}; ship.credits = 20000;
ship.pos.x = 0; ship.pos.y = 1e6; ship.pos.z = 0; ship.dockedAt = null;
const mining = makeStep('MINE', { kind:'seam', x:1e6, y:0,z:0,name:'Regression seam' });
assert.ok(startMission(makeMission({ builtin:true,steps:[mining,makeStep('DOCK',{kind:'best-buyer'})] })));
sim.time = 10; ship.charge = batteryCap(ship) * AP_POWER.floor * 0.5;
for(let i=0;i<10;i++){sim.time++;tickMission(1);assert.equal(mission.stepIx,0);assert.equal(mission.state,'running');}
assert.equal(autopilot.phase,'charge');
ship.charge = batteryCap(ship) * (AP_POWER.floor + AP_POWER.band) / 2;
assert.equal(EXEC.MINE(mining),'flying'); assert.equal(autopilot.phase,'charge');
ship.charge = batteryCap(ship) * (AP_POWER.band + 0.05);
EXEC.MINE(mining);assert.equal(mission.run.mineCharging,undefined);assert.equal(mission.stepIx,0);
ship.charge = 0; sim.time = 40; EXEC.MINE(mining);sim.time=161;
assert.match(EXEC.MINE(mining),/^fail:battery cannot recharge/);
stopMission('test');beginAriaWatch();
// 0.3.88: a hostile contact close by is not, on its own, a reason to stop work.
const yard=stations.find(s=>!s.hostile&&s.hangars?.length);
contacts.length=0;contacts.push({id:'test-threat',relation:'hostile',hp:10,x:ship.pos.x,y:ship.pos.y,z:ship.pos.z});
ariaMind.orders.avoidHostiles=true;ship.dockedAt=null;ship.hull=hullMaxOf(ship);ship.charge=batteryCap(ship);ship.credits=20000;
assert.equal(shouldBreakOff(),null,'whole hull with a drone alongside: keep working');
assert.notEqual(planJob().job,'repair','…and the plan is work, not a safety dock');
ship.hull=hullMaxOf(ship)*0.4;
assert.ok(shouldBreakOff(),'hull under the repair line with contacts close: break off for the yard');
assert.equal(planJob().job,'repair');
contacts.length=0;
assert.equal(shouldBreakOff(),null,'hurt but nothing about: finish the job, repair between jobs');
contacts.push({id:'test-threat',relation:'hostile',hp:10,x:ship.pos.x,y:ship.pos.y,z:ship.pos.z});
ariaMind.orders.avoidHostiles=false;
assert.equal(shouldBreakOff(),null,'the order off: she works on');
ariaMind.orders.avoidHostiles=true;ship.credits=0;
assert.equal(shouldBreakOff(),null,'no money for a single point: a yard run buys nothing');
ship.credits=20000;ship.dockedAt=yard.id;ship.hull=hullMaxOf(ship);
assert.ok(planJob().mission,'docked with a whole hull she undocks to work — no hold timer');
contacts.length=0;
console.log('aria-mining-loop: low battery cannot finish MINE; recharge resumes; stuck power fails explicitly; proximity alone never breaks work off PASS');
