import assert from 'node:assert/strict';
import { sim, launchSim } from '../js/sim/sim.js';
import { ariaMind, resetMind } from '../js/aria/mind.js';
import { wireAria, aria, saveAria } from '../js/aria/aria.js';
import { play, brainNote } from '../js/aria/play.js';
import { mission, EXEC } from '../js/mission/run.js';
import { stations } from '../js/station/stations.js';
import { makeMission, makeStep } from '../js/mission/script.js';
import { makePilot } from '../js/flight/pilot.js';
resetMind();
assert.equal(aria.prefs, ariaMind.prefs);
assert.equal(play.brain, ariaMind.experience);
brainNote('mine', 60, 100, true);
assert.equal(ariaMind.experience.moves.mine.cr, 100);
const store = new Map(); globalThis.localStorage = { setItem: (k,v) => store.set(k,v), getItem: k => store.get(k), removeItem: k => store.delete(k) };
wireAria(); makePilot({name:'Mind Test',complexId:'mining'}); launchSim('Mind Test', 'sol');
ariaMind.orders.reserve = 12345; saveAria();
launchSim('Another Captain', 'sol'); assert.equal(ariaMind.orders.reserve, 15000);
launchSim('Mind Test', 'sol'); assert.equal(ariaMind.orders.reserve, 12345);
assert.equal(aria.prefs, ariaMind.prefs);
const st = stations.find(s => s.stock?.some(g => g.qty > 10)); assert.ok(st);
sim.ship.dockedAt = st.id; sim.ship.credits = 50000;
const good = st.stock.find(g => g.qty > 10);
const step = makeStep('BUY', null, { args: { good: good.id, qty: 2 } });
mission.active = makeMission({ aria: true, builtin: true, steps: [step] });
ariaMind.orders.maxPurchase = 0;
const before = sim.ship.credits;
assert.match(EXEC.BUY(step), /^fail:/);
assert.equal(sim.ship.credits, before, 'career purchases obey current limits at execution');
ariaMind.authority.repairs = false;
sim.ship.hull = 20;
assert.match(EXEC.REPAIR(), /^fail:/);
assert.equal(sim.ship.credits, before, 'revoked repair authority blocks spending');
console.log('ariamind-integration: shared objects, captain switching, purchase guards and revoked repair authority PASS');
