import assert from 'node:assert/strict';
import { ariaMind, resetMind, learnTape, authorize, setOrders, remember, bindPeopleLookup, personMemory, decideMind, explanationPacket, loadMind, saveMind, spendCap, WORKING_FLOOR } from '../js/aria/mind.js';
import { wireRecorder, record, settle, resetRecorder } from '../js/flight/recorder.js';
resetMind();
// 0.3.88: every authority starts granted; unticking one withholds it.
for (const k of Object.keys(ariaMind.authority)) assert.equal(ariaMind.authority[k], true, `${k} starts granted`);
assert.equal(authorize('dismissal').ok, true);
assert.equal(authorize('hiring', { cost: 400, credits: 3000 }).ok, true);
assert.equal(authorize('founding', { cost: 2500, credits: 40000 }).ok, true);
ariaMind.authority.dismissal = false;
assert.equal(authorize('dismissal').ok, false);
assert.equal(ariaMind.pending.at(-1).domain, 'dismissal');
ariaMind.authority.dismissal = true;
assert.equal(authorize('mine').ok, true);
assert.equal(authorize('refit', { cost: 30000, credits: 100000 }).ok, false);
// The reserve guards investments only.
assert.equal(authorize('refit', { cost: 1000, credits: 15500 }).ok, false);
assert.equal(authorize('founding', { cost: 2500, credits: 17000 }).ok, false);
assert.equal(authorize('repair', { cost: 1000, credits: 15500 }).ok, true, 'a repair is never held back by the reserve');
assert.equal(authorize('repair', { cost: 60000, credits: 60000 }).ok, true, '…nor by the purchase ceiling');
assert.equal(authorize('route', { cost: 1000, credits: 1500 }).ok, false, 'cargo keeps the working floor aboard');
assert.equal(authorize('route', { cost: 1000, credits: 1900 }).ok, true);
assert.equal(authorize('treasury', { cost: 90000, credits: 100000 }).ok, true, 'a treasury transfer is not a purchase');
assert.equal(spendCap(20000, 'route'), 20000 - WORKING_FLOOR);
assert.equal(spendCap(100000, 'route'), 25000);
assert.equal(spendCap(20000, 'refit'), 5000);
assert.equal(authorize('repair', { cost: NaN }).ok, false);
setOrders({ reserve: 500, maxPurchase: 2000 });
assert.equal(authorize('repair', { cost: 1000, credits: 2000 }).ok, true);
let t = 0, credits = 100;
resetRecorder();
wireRecorder({ sample: () => ({ t, hull: 0.8, hold: 0.2, cr: credits }), who: () => 'player', captureTaps: false });
record('mission', 'MINE');
assert.equal(ariaMind.learned, 0);
t = 31; credits = 130; settle();
assert.equal(ariaMind.learned, 1);
assert.equal(ariaMind.contexts[0].cr, 30);
assert.equal(learnTape({ by: 'player', s: {}, d: { partial: 1 } }), false);
const combat = ariaMind.risk.combat;
learnTape({ by: 'aria', kind: 'mission', act: 'MINE', s: { hull: 0.2, hz: 1 }, d: { cr: 10, hull: 0, dt: 30 } });
assert.equal(ariaMind.risk.combat, combat, 'own actions never alter captain risk preferences');
for (let i = 0; i < 300; i++) learnTape({ by: 'player', kind: 'test', act: String(i), s: { hull: 0.7 }, d: { cr: 1, dt: 30 } });
assert.equal(ariaMind.contexts.length, 256);
bindPeopleLookup(id => ({ id, name: 'Mara' }));
for (let i = 0; i < 120; i++) remember({ summary: 'Crew event', actors: ['mara'] });
assert.equal(ariaMind.episodes.length, 96);
assert.equal(personMemory('mara').person.name, 'Mara');
decideMind({ action: 'mine', state: { hull: 0.9 }, steps: ['MINE', 'DOCK'], alternatives: [{ action: 'sell' }] });
assert.equal(ariaMind.goals.length, 4);
const packet = explanationPacket(); packet.orders.reserve = 0;
assert.equal(ariaMind.orders.reserve, 500, 'conversation packet is detached from actuators and memory');
const store = new Map(); globalThis.localStorage = { setItem: (k,v) => store.set(k,v), getItem: k => store.get(k) };
saveMind('captain-a'); loadMind('captain-b'); assert.equal(ariaMind.learned, 0);
loadMind('captain-a'); assert.equal(ariaMind.learned, 302); assert.equal(ariaMind.orders.reserve, 500);
// A mind saved by the Core patch (v1) carried its withheld defaults; they are dropped once.
store.set('old', JSON.stringify({ v: 1, orders: { reserve: 9000 }, authority: { hiring: false, founding: false, combat: false, navigation: true }, learned: 7 }));
assert.equal(loadMind('old'), true);
assert.equal(ariaMind.orders.reserve, 9000, 'a v1 mind keeps its orders');
assert.equal(ariaMind.learned, 7);
assert.equal(ariaMind.authority.hiring && ariaMind.authority.founding && ariaMind.authority.combat, true, 'a v1 mind does not keep the withheld defaults');
ariaMind.authority.hiring = false; saveMind('old');
assert.equal(JSON.parse(store.get('old')).v, 2);
loadMind('captain-b'); loadMind('old');
assert.equal(ariaMind.authority.hiring, false, 'a v2 mind keeps what the captain unticked');
console.log('ariamind: authority, recorder settlement, source isolation, bounded memory, people references, goals and persistence PASS');
