import assert from 'node:assert/strict';
import { sim, launchSim } from '../js/sim/sim.js';
import { makePilot } from '../js/flight/pilot.js';
import { stations } from '../js/station/stations.js';
import { contracts, tickContracts, deliverableAt, deliverContracts, boardFor } from '../js/economy/contracts.js';
import { recoverSite } from '../js/sim/salvage.js';
import { roomFor } from '../js/flight/ship.js';
import { chunkMass } from '../js/world/debris.js';

makePilot('Recovery', 'terran', 'salvage', null);
launchSim('Salvage384', 'fixture');
const ship = sim.ship;
ship.hold = {}; ship.cargoCap = 2; ship.dockedAt = null;
ship.salvage = false; ship.powered.ops = true; ship.mods = {};
const job = { good:'iron_ore', qty:6, targets:[{ dwell:6 }] };
assert.equal(recoverSite(job,ship,1).recovered,0);
ship.salvage=true; ship.powered.ops=false;
assert.equal(recoverSite(job,ship,1).recovered,0);
ship.powered.ops=true;
const fits = roomFor(ship,"iron_ore");
assert.equal(recoverSite(job,ship,10).recovered,fits);
assert.equal(job.recovered,fits);
assert.match(recoverSite(job,ship,1).blocked,/Hold full/);
const restored=JSON.parse(JSON.stringify(job));
ship.hold={}; ship.cargoCap=10;
assert.equal(recoverSite(restored,ship,10).recovered,6-fits);
assert.equal(recoverSite(restored,ship,10).recovered,0);
assert.equal(chunkMass({r:100,remainingMass:0.25}),0.25);
ship.hold={}; ship.mods.salvage=2;
assert.equal(recoverSite({good:'iron_ore',qty:6,targets:[{dwell:6}]},ship,1).recovered,2);

// Exercise the actual board, tick, cargo and payout path.
contracts.active.length=0;
ship.hold={}; ship.cargoCap=1000; ship.mods.salvage=1;
const port=stations.find(s=>!s.hostile);
const offered=stations.flatMap(s=>boardFor(s)).filter(a=>a.type==='wreck'||a.type==='pod');
assert.ok(offered.length);
assert.ok(offered.every(a=>a.recovery));
const a={ id:'recovery-test',type:'wreck',mech:'visit',recovery:true,salvage:true,stationId:port.id,stationName:port.name,title:'Test wreck',good:'iron_ore',qty:6,pay:100,progress:0,leg:0,deadline:sim.time+100,targets:[{kind:'point',...ship.pos,dwell:6}],cat:'salvage' };
contracts.active.push(a);
ship.salvage=false; tickContracts(10); assert.equal(a.progress,0);
ship.salvage=true;
ship.pos.x+=100000; tickContracts(10); assert.equal(a.recovered,undefined);
ship.pos.x-=100000;
tickContracts(3); assert.equal(a.recovered,3); assert.equal(a.progress,0);
tickContracts(3); assert.equal(a.progress,1); assert.equal(ship.hold.iron_ore,6);
tickContracts(3); assert.equal(ship.hold.iron_ore,6);
ship.dockedAt=port.id;
assert.ok(deliverableAt(port.id).includes(a));
const credits=ship.credits;
assert.equal(deliverContracts(port.id),100);
assert.equal(ship.credits,credits+100);
assert.equal(ship.hold.iron_ore ?? 0,0);
assert.equal(contracts.active.length,0);
console.log('salvage: powered recovery, capacity, resume data, modifiers, board, site and payout passed');
