/**
 * Industrial complexes and lettered career ladders for a space-age browser RPG.
 *
 * Rank letters follow the requested pattern:
 *   A Survey / Aide  →  B Entry  →  C Journeyman  →  D Proficient  →  E Master
 * then two deep ranks (F Foreman / Director, G Complex authority).
 *
 * After rank D a character may lock a specialization without leaving the main
 * ladder. Specializations add a suffix title and extra unlocks.
 *
 * Pay is in "scrip" (station credits) per cycle. Tune to your economy.
 */

export const RANK_LETTERS = ["A", "B", "C", "D", "E", "F", "G"];

export const COMPLEXES = {
  mining: {
    id: "mining",
    name: "Mining Complex",
    short: "Extraction",
    icon: "⛏️",
    color: "#c4a35a",
    setting:
      "Asteroid belts, ice moons, planetary crust shafts, and claim-beacon grids. Air is metered. Claims are law.",
    primarySkills: ["geology", "heavyOps", "hazardOps"],
    related: ["salvage", "logistics", "energy", "manufacturing"],
    ranks: [
      {
        letter: "A",
        title: "Surveyor",
        honorific: "Surveyor",
        duties:
          "Walk or drone a body. Plant assay spikes. File spectral maps. Flag unstable ice and claim jumpers. You do not cut rock yet; you decide whether anyone should.",
        req: { skills: { geology: 8 }, cycles: 0, certs: ["basic_eva"] },
        pay: 900,
        unlocks: ["hand_spectrometer", "claim_beacon_kit", "survey_drone_mk1"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Miner",
        honorific: "Miner",
        duties:
          "Run a single-head drill or ore sled under a journeyman. Bag, tag, and haul. Learn the difference between a rich vein and a pressure bomb.",
        req: { skills: { geology: 18, heavyOps: 12 }, cycles: 4, certs: ["basic_eva", "ore_handling"] },
        pay: 1400,
        unlocks: ["entry_drill", "ore_sled", "filter_mask_heavy"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Miner",
        honorific: "Journeyman Miner",
        duties:
          "Licensed for vacuum and spin-g shafts. Lead a two-person cut. Set charges within regulation. Sign your own daily yield sheet.",
        req: { skills: { geology: 32, heavyOps: 28, hazardOps: 20 }, cycles: 12, certs: ["vacuum_ops", "blast_card"] },
        pay: 2300,
        unlocks: ["journeyman_rig", "charge_pack", "two_person_claim"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Miner",
        honorific: "Proficient Miner",
        duties:
          "Rare-ore and ice-volatile certification. Plan multi-day cuts. Stake and defend a personal claim. Mentor entry crews.",
        req: { skills: { geology: 48, heavyOps: 44, hazardOps: 36 }, cycles: 28, certs: ["rare_ore", "claim_law"] },
        pay: 3600,
        unlocks: ["proficient_cutter", "personal_claim_license", "crew_bonus_share"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Miner",
        honorific: "Master Miner",
        duties:
          "Own the cut. Train journeymen. Arbitrate claim disputes on-site. Your yield numbers move the complex's quarterly.",
        req: { skills: { geology: 64, heavyOps: 60, hazardOps: 52, command: 24 }, cycles: 50, certs: ["master_ticket"] },
        pay: 5200,
        unlocks: ["master_exoframe", "training_seal", "priority_refinery_window"],
        next: "F",
      },
      {
        letter: "F",
        title: "Mining Foreman",
        honorific: "Foreman",
        duties:
          "Run a shaft, belt gang, or moon pit. Assign shifts, gear, and hazard stand-downs. Answer to the Extractor-General.",
        req: { skills: { geology: 72, heavyOps: 68, command: 40, law: 18 }, cycles: 72, certs: ["foreman_writ"] },
        pay: 7100,
        unlocks: ["foreman_office", "shift_authority", "hazard_override"],
        next: "G",
      },
      {
        letter: "G",
        title: "Extractor-General",
        honorific: "Extractor-General",
        duties:
          "Authority over an entire mining complex: claims, refinery feed, labor contracts, and the emergency seal. Your name is on the ore that builds the yards.",
        req: { skills: { geology: 80, command: 60, law: 36, commerce: 28 }, cycles: 100, certs: ["complex_charter"] },
        pay: 9800,
        unlocks: ["complex_seal", "fleet_tug_priority", "charter_vote"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "belt_harvester",
        name: "Belt Harvester",
        fromRank: "C",
        skills: { navigation: 20, piloting: 16, hazardOps: 30 },
        titleSuffix: "Belter",
        flavor: "Live on the rock. Spin-dock cutters, chase icebergs, never trust a chart more than a year old.",
        unlocks: ["belt_cutter_lease", "ice_tether"],
      },
      {
        id: "deep_core",
        name: "Deep Core Specialist",
        fromRank: "D",
        skills: { geology: 55, hazardOps: 45, energySystems: 20 },
        titleSuffix: "Deep-Core",
        flavor: "Planetary and moon crust. Heat, pressure, and the long elevator down.",
        unlocks: ["core_drill_auth", "magma_tap_permit"],
      },
      {
        id: "exotic_extract",
        name: "Exotic Matter Extractor",
        fromRank: "E",
        skills: { geology: 70, research: 30, hazardOps: 60 },
        titleSuffix: "Exotic",
        flavor: "Helium-3 ices, radioactives, and the quietly restricted list. Escorts recommended.",
        unlocks: ["restricted_ore_license", "escort_requisition"],
      },
    ],
  },

  healthcare: {
    id: "healthcare",
    name: "Healthcare Complex",
    short: "Life Sciences",
    icon: "✚",
    color: "#e36d6d",
    setting:
      "Spin-hospitals, trauma bays on yards, cryo stacks, and quarantine rings. Death is negotiable. Licenses are not.",
    primarySkills: ["firstAid", "surgery", "xenomed"],
    related: ["research", "agriculture", "security"],
    ranks: [
      {
        letter: "A",
        title: "Triage Aide",
        honorific: "Aide",
        duties:
          "Sort the walking from the dying. Fetch kits, log vitals, keep the bay floor clear. You do not diagnose; you keep people alive until someone who can arrives.",
        req: { skills: { firstAid: 8 }, cycles: 0, certs: ["aid_badge"] },
        pay: 1000,
        unlocks: ["trauma_kit_basic", "stretcher_drone"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Medic",
        honorific: "Medic",
        duties:
          "Corpsman work: airways, bleeds, burns, decompression. Ride the ambulance sled. Call the physician when the protocol ends.",
        req: { skills: { firstAid: 20, psychiatry: 8 }, cycles: 5, certs: ["emt_ticket"] },
        pay: 1600,
        unlocks: ["field_defib", "ambulance_sled", "meds_schedule_ii"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Physician",
        honorific: "Physician",
        duties:
          "Licensed general practice for station and ship crews. Write holds, clear EVA, treat the ordinary catalogue of space injuries.",
        req: { skills: { firstAid: 36, surgery: 22, psychiatry: 16 }, cycles: 16, certs: ["practice_license"] },
        pay: 2800,
        unlocks: ["clinic_hours", "script_pad", "medbay_access_full"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Specialist",
        honorific: "Specialist",
        duties:
          "Hold a chair: trauma, xenopath, cryo, or psych. Consult across complexes. Your name on a chart carries weight in court.",
        req: { skills: { firstAid: 48, surgery: 40, xenomed: 24 }, cycles: 32, certs: ["specialty_board"] },
        pay: 4200,
        unlocks: ["or_block_time", "consult_fee", "quarantine_key"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Clinician",
        honorific: "Master Clinician",
        duties:
          "Teach residents. Take the cases no one else will touch. Set complex protocol. When the yard has a mass-casualty, they page you.",
        req: { skills: { surgery: 62, firstAid: 58, xenomed: 40, command: 22 }, cycles: 55, certs: ["master_board"] },
        pay: 6100,
        unlocks: ["teaching_seal", "protocol_author", "priority_or"],
        next: "F",
      },
      {
        letter: "F",
        title: "Chief of Service",
        honorific: "Chief",
        duties:
          "Run a department: trauma, xenomed, cryo, or psych. Staffing, ethics board, and the budget that keeps the stacks cold.",
        req: { skills: { command: 44, law: 20, surgery: 70 }, cycles: 78, certs: ["chief_writ"] },
        pay: 8000,
        unlocks: ["department_budget", "hire_residents", "ethics_vote"],
        next: "G",
      },
      {
        letter: "G",
        title: "Medical Director",
        honorific: "Director",
        duties:
          "The Healthcare Complex answers to you. Epidemic authority, revival policy, and the quiet list of who gets a new body.",
        req: { skills: { command: 62, law: 36, genetics: 28 }, cycles: 110, certs: ["complex_charter"] },
        pay: 10500,
        unlocks: ["complex_seal", "revival_policy", "epidemic_override"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "trauma",
        name: "Trauma & Combat Medicine",
        fromRank: "C",
        skills: { firstAid: 40, surgery: 30, hazardOps: 16 },
        titleSuffix: "Trauma",
        flavor: "Yards, mines, and boarding actions. Speed over elegance.",
        unlocks: ["combat_surgeon_kit", "mass_cas_lead"],
      },
      {
        id: "xenomedicine",
        name: "Xenomedicine",
        fromRank: "D",
        skills: { xenomed: 40, research: 24, genetics: 16 },
        titleSuffix: "Xeno",
        flavor: "Patients who do not share your skeleton, or your chemistry.",
        unlocks: ["xeno_ward", "pathogen_vault"],
      },
      {
        id: "cryo_revival",
        name: "Cryonics & Revival",
        fromRank: "D",
        skills: { cryonics: 40, firstAid: 36, electronics: 16 },
        titleSuffix: "Cryo",
        flavor: "The long sleep and the harder waking. Stacks do not forgive sloppy thaw.",
        unlocks: ["cryo_stack_keys", "revival_theater"],
      },
      {
        id: "augmetics",
        name: "Genetic Augmentation",
        fromRank: "E",
        skills: { genetics: 50, surgery: 50, law: 20 },
        titleSuffix: "Augment",
        flavor: "Licensed edits only. Unlicensed work is a different complex entirely.",
        unlocks: ["aug_clinic", "somatic_license"],
      },
    ],
  },

  shipyard: {
    id: "shipyard",
    name: "Shipyard Complex",
    short: "Yards",
    icon: "🚢",
    color: "#6b8cae",
    setting:
      "Drydocks, slipways, and the dark side of a station where hulls grow by the meter. A bad weld kills later, in vacuum, with an audience of none.",
    primarySkills: ["hullcraft", "propulsion", "electronics"],
    related: ["manufacturing", "energy", "logistics", "navigation"],
    ranks: [
      {
        letter: "A",
        title: "Yard Runner",
        honorific: "Runner",
        duties:
          "Fetch plate, carry tools, hold the lamp. Learn the slip numbers and which cranes will take your arm off. Survey hulls before you ever touch a torch.",
        req: { skills: { hullcraft: 6 }, cycles: 0, certs: ["yard_badge"] },
        pay: 850,
        unlocks: ["yard_radio", "plate_sled"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Shipfitter",
        honorific: "Shipfitter",
        duties:
          "Fit frames and skin under a journeyman. Grind, tack, and pressure-test compartments. Your first certified seam is a rite.",
        req: { skills: { hullcraft: 18, electronics: 10 }, cycles: 5, certs: ["torch_card", "pressure_test"] },
        pay: 1500,
        unlocks: ["fitter_rig", "certified_welder"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Hullwright",
        honorific: "Hullwright",
        duties:
          "Own a section. Sign the integrity log. Install secondary systems. Lead two fitters through a refit window.",
        req: { skills: { hullcraft: 34, electronics: 22, propulsion: 16 }, cycles: 14, certs: ["section_ticket"] },
        pay: 2500,
        unlocks: ["section_lead", "integrity_stamp"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Naval Architect",
        honorific: "Architect-Tech",
        duties:
          "Translate a print into a living hull. Balance mass, heat, and berthing. Catch the errors that would crack a keel on first burn.",
        req: { skills: { hullcraft: 50, propulsion: 36, electronics: 36, materials: 24 }, cycles: 30, certs: ["architect_seal"] },
        pay: 3900,
        unlocks: ["print_authority", "keel_review"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Shipwright",
        honorific: "Master Shipwright",
        duties:
          "Your mark on a hull is a warranty. Capitals, liners, and the ugly specials the navy pretends not to order. Train architects.",
        req: { skills: { hullcraft: 66, propulsion: 52, command: 24 }, cycles: 54, certs: ["master_wright"] },
        pay: 5800,
        unlocks: ["wright_mark", "capital_slip_access"],
        next: "F",
      },
      {
        letter: "F",
        title: "Drydock Foreman",
        honorific: "Dock Foreman",
        duties:
          "One slip or an entire dock arm. Schedule steel, labor, and launch windows. Weather the owner's rage when a keel slips.",
        req: { skills: { command: 42, supplyChain: 28, hullcraft: 72 }, cycles: 76, certs: ["foreman_writ"] },
        pay: 7600,
        unlocks: ["dock_schedule", "launch_authority"],
        next: "G",
      },
      {
        letter: "G",
        title: "Yardmaster",
        honorific: "Yardmaster",
        duties:
          "The Shipyard Complex is yours: slips, labor guilds, military contracts, and the right to refuse a hull that will kill its crew.",
        req: { skills: { command: 64, law: 32, commerce: 30 }, cycles: 108, certs: ["complex_charter"] },
        pay: 10200,
        unlocks: ["complex_seal", "contract_veto", "keel_naming"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "capital_hulls",
        name: "Capital Hulls",
        fromRank: "D",
        skills: { hullcraft: 55, command: 20, energySystems: 24 },
        titleSuffix: "Capital",
        flavor: "Kilometers of spine. Years of work. One bad frame and a city dies in the dark.",
        unlocks: ["capital_tools", "spine_crane"],
      },
      {
        id: "drive_yards",
        name: "Drive Systems",
        fromRank: "C",
        skills: { propulsion: 40, energySystems: 28, electronics: 24 },
        titleSuffix: "Drives",
        flavor: "The heart of the ship. Fusion bottles, torch bells, and the things that are not discussed in open manuals.",
        unlocks: ["drive_bay", "bottle_ticket"],
      },
      {
        id: "refit_stealth",
        name: "Military & Stealth Refit",
        fromRank: "E",
        skills: { electronics: 50, hullcraft: 50, security: 20 },
        titleSuffix: "Black-Slip",
        flavor: "Work that does not appear on the public board. NDAs measured in decades.",
        unlocks: ["black_slip", "emission_lab"],
      },
    ],
  },

  manufacturing: {
    id: "manufacturing",
    name: "Component Manufacturing Complex",
    short: "Foundry",
    icon: "⚙️",
    color: "#8a7a6b",
    setting:
      "Print halls, sinter lines, clean rooms, and the foundry floor where raw ore becomes the parts every other complex begs for.",
    primarySkills: ["precisionFab", "materials", "electronics"],
    related: ["mining", "shipyard", "energy", "research"],
    ranks: [
      {
        letter: "A",
        title: "Parts Runner",
        honorific: "Runner",
        duties:
          "Move bins, scan lots, watch the line for jams. Learn which feedstock is hungry and which machine will take a finger.",
        req: { skills: { precisionFab: 6 }, cycles: 0, certs: ["floor_badge"] },
        pay: 800,
        unlocks: ["lot_scanner", "line_radio"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Assembler",
        honorific: "Assembler",
        duties:
          "Tend a station on the line. Torque to spec. Fail a part rather than pass a lie. First quality stamp is supervised.",
        req: { skills: { precisionFab: 18, electronics: 10 }, cycles: 4, certs: ["qc_level_1"] },
        pay: 1350,
        unlocks: ["assembler_bench", "torque_set"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Fabricator",
        honorific: "Fabricator",
        duties:
          "Run a cell. Change over tools. Write a deviation. Your parts fly, dock, and keep air in lungs.",
        req: { skills: { precisionFab: 34, materials: 20, electronics: 20 }, cycles: 13, certs: ["cell_ticket"] },
        pay: 2400,
        unlocks: ["fab_cell", "deviation_pad"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Machinist",
        honorific: "Machinist",
        duties:
          "Tight-tolerance work: bearings, valves, sensor housings, drive vanes. You are the reason a ship does not shake itself apart.",
        req: { skills: { precisionFab: 50, materials: 38, electronics: 32 }, cycles: 28, certs: ["tolerance_ticket"] },
        pay: 3700,
        unlocks: ["cnc_priority", "metrology_lab"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Component Engineer",
        honorific: "Master Engineer",
        duties:
          "Design the part, not just cut it. Qualify a new alloy or a new print. Train the floor. Sign flight-critical lots.",
        req: { skills: { precisionFab: 64, materials: 54, research: 24, command: 20 }, cycles: 52, certs: ["flight_critical"] },
        pay: 5500,
        unlocks: ["design_authority", "lot_signoff"],
        next: "F",
      },
      {
        letter: "F",
        title: "Foundry Chief",
        honorific: "Foundry Chief",
        duties:
          "An entire hall or clean-room wing. Throughput, scrap rate, and the political fight for feedstock from Mining.",
        req: { skills: { command: 42, supplyChain: 30, precisionFab: 70 }, cycles: 74, certs: ["chief_writ"] },
        pay: 7400,
        unlocks: ["hall_budget", "feedstock_priority"],
        next: "G",
      },
      {
        letter: "G",
        title: "Production Architect",
        honorific: "Production Architect",
        duties:
          "The Manufacturing Complex's mind. Which lines exist, which secrets stay in-house, and which contracts keep the yards alive.",
        req: { skills: { command: 62, commerce: 34, nanofab: 28 }, cycles: 105, certs: ["complex_charter"] },
        pay: 10000,
        unlocks: ["complex_seal", "line_charter", "restricted_print"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "microelectronics",
        name: "Microelectronics",
        fromRank: "C",
        skills: { electronics: 40, precisionFab: 30, dataOps: 16 },
        titleSuffix: "Boards",
        flavor: "Clean rooms, yield charts, and the chips that think for ships.",
        unlocks: ["cleanroom_pass", "mask_set"],
      },
      {
        id: "structural_alloys",
        name: "Structural Alloys",
        fromRank: "C",
        skills: { materials: 40, energySystems: 16, heavyOps: 16 },
        titleSuffix: "Alloys",
        flavor: "The bones. Pour, roll, age, and test until the numbers stop lying.",
        unlocks: ["pour_floor", "aging_ovens"],
      },
      {
        id: "nanoline",
        name: "Nanofabrication",
        fromRank: "E",
        skills: { nanofab: 50, research: 30, hazardOps: 24 },
        titleSuffix: "Nano",
        flavor: "Assemblers that eat feedstock and, if you are careless, the building.",
        unlocks: ["assembler_vault", "grey_goo_kill"],
      },
    ],
  },

  logistics: {
    id: "logistics",
    name: "Logistics Complex",
    short: "Freight",
    icon: "📦",
    color: "#d4a017",
    setting:
      "Docks, warehouses, ice-haulers, and the manifests that keep a habitat from starving. A late pallet is a political event.",
    primarySkills: ["supplyChain", "navigation", "commerce"],
    related: ["mining", "manufacturing", "navigation", "commerce"],
    ranks: [
      {
        letter: "A",
        title: "Dock Clerk",
        honorific: "Clerk",
        duties:
          "Scan crates, match seals, argue with loaders about the manifest. Survey incoming holds for undeclared mass.",
        req: { skills: { supplyChain: 8 }, cycles: 0, certs: ["dock_badge"] },
        pay: 880,
        unlocks: ["manifest_pad", "seal_gun"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Stevedore",
        honorific: "Stevedore",
        duties:
          "Load and lash. Drive a dock mule. Learn that a poorly tied cryo-pallet becomes a missile at 0.3g.",
        req: { skills: { supplyChain: 16, heavyOps: 12 }, cycles: 4, certs: ["lash_card"] },
        pay: 1450,
        unlocks: ["dock_mule", "g_lash_kit"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Hauler",
        honorific: "Hauler",
        duties:
          "Take a scheduled run. Own the hold. File delays. Know which lanes are honest and which are merely mapped.",
        req: { skills: { supplyChain: 32, navigation: 22, piloting: 16 }, cycles: 12, certs: ["haul_ticket"] },
        pay: 2400,
        unlocks: ["hold_lease_small", "lane_book"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Route Master",
        honorific: "Route Master",
        duties:
          "Design multi-leg circuits. Hedge mass and time. Keep three colonies and a yard from missing the same part.",
        req: { skills: { supplyChain: 48, navigation: 36, commerce: 28 }, cycles: 28, certs: ["route_seal"] },
        pay: 3800,
        unlocks: ["circuit_authority", "priority_docking"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Logistician",
        honorific: "Master Logistician",
        duties:
          "The person other complexes call when the chain snaps. Build contingency, train haulers, and price risk in public.",
        req: { skills: { supplyChain: 64, commerce: 44, command: 24 }, cycles: 50, certs: ["master_log"] },
        pay: 5600,
        unlocks: ["contingency_budget", "fleet_slot"],
        next: "F",
      },
      {
        letter: "F",
        title: "Fleet Quartermaster",
        honorific: "Quartermaster",
        duties:
          "A freight fleet or a habitat's entire intake. Fuel, spare parts, food, and the ugly specials.",
        req: { skills: { command: 42, supplyChain: 72, law: 20 }, cycles: 72, certs: ["qm_writ"] },
        pay: 7500,
        unlocks: ["fleet_manifest", "ration_authority"],
        next: "G",
      },
      {
        letter: "G",
        title: "Supply Chain Director",
        honorific: "Director",
        duties:
          "The Logistics Complex. Who eats, who builds, who waits. Embargoes and relief runs start on your desk.",
        req: { skills: { command: 62, commerce: 50, law: 34 }, cycles: 100, certs: ["complex_charter"] },
        pay: 10100,
        unlocks: ["complex_seal", "embargo_vote", "relief_flag"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "hazcargo",
        name: "Hazardous Cargo",
        fromRank: "C",
        skills: { hazardOps: 28, supplyChain: 30, law: 12 },
        titleSuffix: "Hazmat",
        flavor: "Radioactives, volatiles, live samples. One leak and the dock becomes a story.",
        unlocks: ["haz_hold", "spill_team"],
      },
      {
        id: "coldsleep",
        name: "Cold-Sleep Transport",
        fromRank: "D",
        skills: { cryonics: 20, lifeSupport: 24, piloting: 24 },
        titleSuffix: "Sleeper",
        flavor: "Passengers who must not wake. Stacks, monitors, and the ethics of a missed window.",
        unlocks: ["sleeper_hold", "thaw_protocol"],
      },
      {
        id: "colony_jit",
        name: "Colony Just-in-Time",
        fromRank: "D",
        skills: { supplyChain: 50, agriculture: 12, construction: 12 },
        titleSuffix: "Colony",
        flavor: "A habitat three jumps out lives or dies on your schedule.",
        unlocks: ["colony_contract", "emergency_drop"],
      },
    ],
  },

  energy: {
    id: "energy",
    name: "Energy Complex",
    short: "Power",
    icon: "⚡",
    color: "#f0c14b",
    setting:
      "Reactor halls, solar farms on the dayside, radiator forests, and the grid that every other complex treats as weather.",
    primarySkills: ["energySystems", "electronics", "hazardOps"],
    related: ["manufacturing", "shipyard", "research", "construction"],
    ranks: [
      {
        letter: "A",
        title: "Grid Observer",
        honorific: "Observer",
        duties:
          "Walk the bus rooms. Log temperatures. Report a flicker before it becomes a blackout. You do not touch the bottle.",
        req: { skills: { energySystems: 8 }, cycles: 0, certs: ["grid_badge"] },
        pay: 950,
        unlocks: ["grid_pad", "ir_glasses"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Power Tech",
        honorific: "Power Tech",
        duties:
          "Swap breakers, clean radiators, assist a scram drill. Learn the sound a healthy reactor makes.",
        req: { skills: { energySystems: 20, electronics: 12 }, cycles: 5, certs: ["lv_ticket"] },
        pay: 1550,
        unlocks: ["tech_rig", "scram_drill"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Reactor Hand",
        honorific: "Reactor Hand",
        duties:
          "Stand a watch. Adjust load. Sign the log that says the bottle is honest. Lead two techs through a planned outage.",
        req: { skills: { energySystems: 36, electronics: 24, hazardOps: 18 }, cycles: 15, certs: ["watch_ticket"] },
        pay: 2600,
        unlocks: ["watch_chair", "load_desk"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Systems Engineer",
        honorific: "Systems Engineer",
        duties:
          "Balance a habitat's hunger against a yard's welders. Design redundant feeds. Catch the cascade three steps out.",
        req: { skills: { energySystems: 52, electronics: 38, lifeSupport: 20 }, cycles: 32, certs: ["systems_seal"] },
        pay: 4000,
        unlocks: ["cascade_model", "feed_priority"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Power Engineer",
        honorific: "Master Engineer",
        duties:
          "Qualify a new plant. Teach the watch. Your signature says a city may keep its lights.",
        req: { skills: { energySystems: 68, command: 24, research: 20 }, cycles: 56, certs: ["master_plant"] },
        pay: 5900,
        unlocks: ["plant_qualify", "teaching_seal"],
        next: "F",
      },
      {
        letter: "F",
        title: "Plant Chief",
        honorific: "Plant Chief",
        duties:
          "One reactor, one solar farm, or a radiator forest. Crew, fuel, and the politics of who gets load-shed first.",
        req: { skills: { command: 44, energySystems: 74, law: 16 }, cycles: 78, certs: ["chief_writ"] },
        pay: 7800,
        unlocks: ["shed_authority", "fuel_budget"],
        next: "G",
      },
      {
        letter: "G",
        title: "Grid Director",
        honorific: "Grid Director",
        duties:
          "The Energy Complex. Inter-habitat ties, military reserve power, and the right to darken a dock.",
        req: { skills: { command: 64, law: 32, commerce: 24 }, cycles: 110, certs: ["complex_charter"] },
        pay: 10400,
        unlocks: ["complex_seal", "blackout_vote", "reserve_flag"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "fusion_watch",
        name: "Fusion Watch",
        fromRank: "C",
        skills: { energySystems: 40, hazardOps: 28, materials: 16 },
        titleSuffix: "Fusion",
        flavor: "The bottle. Beautiful, loud, and unforgiving.",
        unlocks: ["bottle_chair", "scram_override"],
      },
      {
        id: "solar_radiator",
        name: "Collect & Reject",
        fromRank: "C",
        skills: { energySystems: 34, construction: 20, navigation: 12 },
        titleSuffix: "Array",
        flavor: "Square kilometers of sail and fin. Micrometeorites are a lifestyle.",
        unlocks: ["array_cart", "fin_yard"],
      },
      {
        id: "exotic_power",
        name: "Exotic Power",
        fromRank: "E",
        skills: { energySystems: 70, research: 36, hazardOps: 40 },
        titleSuffix: "Exotic",
        flavor: "Things the charter mentions only in annexes. Escorts. NDAs. Good health insurance.",
        unlocks: ["annex_lab", "containment_key"],
      },
    ],
  },

  construction: {
    id: "construction",
    name: "Habitat Construction Complex",
    short: "Works",
    icon: "🏗️",
    color: "#7d6b5a",
    setting:
      "Print-heads over craters, spin-habitat ribs, dock arms growing into the dark. Architecture here is a pressure vessel with windows.",
    primarySkills: ["construction", "lifeSupport", "materials"],
    related: ["manufacturing", "energy", "terraforming", "logistics"],
    ranks: [
      {
        letter: "A",
        title: "Site Surveyor",
        honorific: "Surveyor",
        duties:
          "Stake a pad. Scan regolith. Mark buried ice and old graves. The print-head does not start until you sign.",
        req: { skills: { construction: 8, geology: 6 }, cycles: 0, certs: ["site_badge"] },
        pay: 900,
        unlocks: ["site_spikes", "regolith_probe"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Builder",
        honorific: "Builder",
        duties:
          "Tend print-heads, set forms, hang life-support trunk. Learn that a 2mm gap is a future funeral.",
        req: { skills: { construction: 18, lifeSupport: 10 }, cycles: 5, certs: ["print_card"] },
        pay: 1480,
        unlocks: ["builder_rig", "trunk_kit"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Habitat Tech",
        honorific: "Habitat Tech",
        duties:
          "Own a bay or a rib section. Pressure-test. Lead a small crew through a night pour.",
        req: { skills: { construction: 34, lifeSupport: 24, materials: 16 }, cycles: 14, certs: ["section_ticket"] },
        pay: 2450,
        unlocks: ["section_keys", "pressure_log"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Works Engineer",
        honorific: "Works Engineer",
        duties:
          "Translate a habitat print into a livable machine. Spin balance, thermal, and the thousand pipes no one photographs.",
        req: { skills: { construction: 50, lifeSupport: 40, energySystems: 22 }, cycles: 30, certs: ["works_seal"] },
        pay: 3850,
        unlocks: ["print_authority", "spin_model"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Architect",
        honorific: "Master Architect",
        duties:
          "Sign a habitat. Your name lives on the dedication plate and, if you were sloppy, on the inquest.",
        req: { skills: { construction: 66, command: 24, materials: 40 }, cycles: 54, certs: ["architect_mark"] },
        pay: 5700,
        unlocks: ["dedication_plate", "inquest_standing"],
        next: "F",
      },
      {
        letter: "F",
        title: "Works Foreman",
        honorific: "Works Foreman",
        duties:
          "A whole arm, dome, or dock expansion. Labor guilds, print feedstock, and weather delays that are actually politics.",
        req: { skills: { command: 44, supplyChain: 28, construction: 72 }, cycles: 76, certs: ["foreman_writ"] },
        pay: 7600,
        unlocks: ["arm_budget", "guild_table"],
        next: "G",
      },
      {
        letter: "G",
        title: "Habitat Chancellor",
        honorific: "Chancellor",
        duties:
          "The Construction Complex. What gets built, what gets condemned, and who lives in the new ring.",
        req: { skills: { command: 64, law: 34, commerce: 28 }, cycles: 108, certs: ["complex_charter"] },
        pay: 10300,
        unlocks: ["complex_seal", "condemn_writ", "ring_charter"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "spin_habitats",
        name: "Spin Habitats",
        fromRank: "D",
        skills: { construction: 55, navigation: 16, lifeSupport: 36 },
        titleSuffix: "Spin",
        flavor: "Centrifugal cities. Get the balance wrong and breakfast becomes a weapon.",
        unlocks: ["spoke_yard", "balance_lab"],
      },
      {
        id: "regolith_print",
        name: "Regolith Print",
        fromRank: "C",
        skills: { construction: 36, geology: 24, materials: 24 },
        titleSuffix: "Print",
        flavor: "Make a city from the ground it sits on. Sinter, bind, and pray the ice was mapped.",
        unlocks: ["print_head_heavy", "sinter_yard"],
      },
      {
        id: "dock_arms",
        name: "Dock & Slip Construction",
        fromRank: "D",
        skills: { construction: 50, hullcraft: 24, heavyOps: 20 },
        titleSuffix: "Docks",
        flavor: "The interface between world and ship. Everyone hates you until they need a berth.",
        unlocks: ["slip_forms", "clamp_forge"],
      },
    ],
  },

  agriculture: {
    id: "agriculture",
    name: "Agriculture & Bioproduction Complex",
    short: "Agri",
    icon: "🌿",
    color: "#5a8f5a",
    setting:
      "Ring farms, mycovats, protein towers, and the smell of wet earth in a place that has never seen rain. Calories are strategy.",
    primarySkills: ["agriculture", "lifeSupport", "genetics"],
    related: ["healthcare", "research", "logistics", "terraforming"],
    ranks: [
      {
        letter: "A",
        title: "Bay Aide",
        honorific: "Aide",
        duties:
          "Water, pick, log wilt. Learn which racks are hungry and which spores are not your friends.",
        req: { skills: { agriculture: 8 }, cycles: 0, certs: ["bay_badge"] },
        pay: 820,
        unlocks: ["bay_kit", "spore_mask"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Grower",
        honorific: "Grower",
        duties:
          "Run a rack or a vat shift. Mix nutrient. Cull. Your first certified harvest feeds a gallery.",
        req: { skills: { agriculture: 18, lifeSupport: 10 }, cycles: 4, certs: ["harvest_card"] },
        pay: 1380,
        unlocks: ["grower_rig", "nutrient_desk"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Cultivator",
        honorific: "Cultivator",
        duties:
          "Own a bay. Fight blight. Balance O2 contribution against calorie targets. Lead two aides through a crop turn.",
        req: { skills: { agriculture: 34, lifeSupport: 22, genetics: 12 }, cycles: 13, certs: ["bay_ticket"] },
        pay: 2350,
        unlocks: ["bay_keys", "blight_protocol"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Bioengineer",
        honorific: "Bioengineer",
        duties:
          "Tune strains. Design a rotation that does not collapse. Feed a yard expansion without stealing from the hospital.",
        req: { skills: { agriculture: 50, genetics: 32, lifeSupport: 32 }, cycles: 28, certs: ["strain_seal"] },
        pay: 3650,
        unlocks: ["strain_lab", "rotation_authority"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Agronomist",
        honorific: "Master Agronomist",
        duties:
          "The person who keeps famine theoretical. Qualify a new crop for a new world. Teach the bays.",
        req: { skills: { agriculture: 66, genetics: 48, command: 22 }, cycles: 52, certs: ["master_agri"] },
        pay: 5400,
        unlocks: ["world_qualify", "teaching_seal"],
        next: "F",
      },
      {
        letter: "F",
        title: "Ring Farm Chief",
        honorific: "Farm Chief",
        duties:
          "A whole ring or tower stack. Water rights, spore incidents, and the union that picks at 0400.",
        req: { skills: { command: 42, supplyChain: 24, agriculture: 72 }, cycles: 74, certs: ["chief_writ"] },
        pay: 7300,
        unlocks: ["water_rights", "shift_table"],
        next: "G",
      },
      {
        letter: "G",
        title: "Bioproduction Director",
        honorific: "Director",
        duties:
          "The Agri Complex. Who eats fresh, who eats vat, and which strains leave the station.",
        req: { skills: { command: 62, law: 28, commerce: 28 }, cycles: 104, certs: ["complex_charter"] },
        pay: 9900,
        unlocks: ["complex_seal", "export_strain", "ration_vote"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "hydroponics",
        name: "Hydroponic Rings",
        fromRank: "C",
        skills: { agriculture: 36, lifeSupport: 28 },
        titleSuffix: "Hydro",
        flavor: "Green light and white roots. The classic closed-loop farm.",
        unlocks: ["ring_cart", "spectrum_desk"],
      },
      {
        id: "mycovats",
        name: "Mycoculture & Protein",
        fromRank: "C",
        skills: { agriculture: 34, genetics: 20, xenomed: 8 },
        titleSuffix: "Vats",
        flavor: "Towers that smell like a forest floor. Efficient. Unphotogenic. Essential.",
        unlocks: ["vat_hall", "protein_line"],
      },
      {
        id: "seed_vault",
        name: "Strain & Seed Vault",
        fromRank: "E",
        skills: { genetics: 50, research: 28, law: 16 },
        titleSuffix: "Vault",
        flavor: "The library of what a species may eat in a century. Theft is treason-adjacent.",
        unlocks: ["vault_keys", "strain_charter"],
      },
    ],
  },

  research: {
    id: "research",
    name: "Research & Science Complex",
    short: "Labs",
    icon: "🔬",
    color: "#6a8caf",
    setting:
      "Clean labs, dirty field tents, telescope arrays, and the peer-review that decides whether a discovery is a paper or a weapon.",
    primarySkills: ["research", "dataOps", "electronics"],
    related: ["healthcare", "energy", "manufacturing", "terraforming"],
    ranks: [
      {
        letter: "A",
        title: "Lab Aide",
        honorific: "Aide",
        duties:
          "Wash glass, log samples, do not open the wrong fridge. Survey literature you do not yet understand.",
        req: { skills: { research: 8 }, cycles: 0, certs: ["lab_badge"] },
        pay: 920,
        unlocks: ["sample_kit", "library_pass"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Researcher",
        honorific: "Researcher",
        duties:
          "Run a protocol. Write a methods section that is not a lie. Present a poster that survives questions.",
        req: { skills: { research: 20, dataOps: 12 }, cycles: 6, certs: ["methods_card"] },
        pay: 1600,
        unlocks: ["bench_time", "poster_slot"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Scientist",
        honorific: "Scientist",
        duties:
          "Own a small study. File grants. Supervise aides. Publish or the complex notices.",
        req: { skills: { research: 36, dataOps: 24, electronics: 16 }, cycles: 16, certs: ["pi_ticket"] },
        pay: 2700,
        unlocks: ["study_lead", "grant_desk"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Investigator",
        honorific: "Investigator",
        duties:
          "A program, not a paper. Field sites. Inter-complex collaboration. The first time a finding changes a yard spec.",
        req: { skills: { research: 52, dataOps: 36, command: 16 }, cycles: 34, certs: ["program_seal"] },
        pay: 4100,
        unlocks: ["field_budget", "spec_memo"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Scientist",
        honorific: "Master Scientist",
        duties:
          "Set a field's questions. Train investigators. Sit on the board that decides what must not be built.",
        req: { skills: { research: 68, command: 28, law: 18 }, cycles: 58, certs: ["master_fellow"] },
        pay: 6000,
        unlocks: ["board_seat", "embargo_recommend"],
        next: "F",
      },
      {
        letter: "F",
        title: "Laboratory Director",
        honorific: "Lab Director",
        duties:
          "A wing or an array. Staff, secrets, and the visitors from Security who smile too much.",
        req: { skills: { command: 46, research: 74, law: 24 }, cycles: 80, certs: ["director_writ"] },
        pay: 7900,
        unlocks: ["wing_budget", "clearance_desk"],
        next: "G",
      },
      {
        letter: "G",
        title: "Chancellor of Inquiry",
        honorific: "Chancellor",
        duties:
          "The Research Complex. What is funded, what is classified, and what is burned.",
        req: { skills: { command: 66, law: 36, commerce: 22 }, cycles: 112, certs: ["complex_charter"] },
        pay: 10600,
        unlocks: ["complex_seal", "classify_writ", "burn_order"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "field_science",
        name: "Field Science",
        fromRank: "C",
        skills: { research: 34, geology: 16, hazardOps: 16 },
        titleSuffix: "Field",
        flavor: "Tents, samples, and the discovery that the map was optimistic.",
        unlocks: ["field_lab", "sample_vault"],
      },
      {
        id: "applied_lab",
        name: "Applied Industrial Science",
        fromRank: "D",
        skills: { research: 50, materials: 24, energySystems: 16 },
        titleSuffix: "Applied",
        flavor: "Make the yards faster, the farms denser, the reactors quieter.",
        unlocks: ["pilot_line", "spec_change"],
      },
      {
        id: "xeno_inquiry",
        name: "Xeno & Anomaly Studies",
        fromRank: "E",
        skills: { research: 70, xenomed: 24, law: 24 },
        titleSuffix: "Xeno",
        flavor: "Things that should not be here. Papers that will not be public.",
        unlocks: ["anomaly_wing", "containment_obs"],
      },
    ],
  },

  security: {
    id: "security",
    name: "Security & Defense Complex",
    short: "Security",
    icon: "🛡️",
    color: "#6b6b6b",
    setting:
      "Armories, lockups, customs rings, and the thin line between a habitat and a riot. Force is a tool. Doctrine is the manual.",
    primarySkills: ["security", "law", "command"],
    related: ["healthcare", "logistics", "navigation", "research"],
    ranks: [
      {
        letter: "A",
        title: "Watch Cadet",
        honorific: "Cadet",
        duties:
          "Walk a beat with a senior. Learn doors, codes, and when not to draw. Survey crowds before you police them.",
        req: { skills: { security: 8 }, cycles: 0, certs: ["cadet_badge"] },
        pay: 1000,
        unlocks: ["watch_radio", "soft_baton"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Officer",
        honorific: "Officer",
        duties:
          "Customs, patrol, first response. Write a report that will be read in court. Do not invent law.",
        req: { skills: { security: 20, law: 12 }, cycles: 5, certs: ["officer_ticket"] },
        pay: 1650,
        unlocks: ["sidearm_license", "hold_keys"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Constable",
        honorific: "Constable",
        duties:
          "Lead a pair. Own a sector for a shift. Handle boarding assists and claim-jump calls from Mining.",
        req: { skills: { security: 36, law: 24, firstAid: 12 }, cycles: 14, certs: ["sector_ticket"] },
        pay: 2600,
        unlocks: ["sector_lead", "boarding_kit"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Inspector",
        honorific: "Inspector",
        duties:
          "Investigations, not just patrol. Follow cargo, money, and the quiet people in Research. Testify.",
        req: { skills: { security: 50, law: 40, dataOps: 20 }, cycles: 30, certs: ["inspector_seal"] },
        pay: 4000,
        unlocks: ["case_authority", "warrant_desk"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Warden",
        honorific: "Warden",
        duties:
          "Doctrine, training, and the hard calls. When a complex goes wrong, you decide the continuum of force.",
        req: { skills: { security: 66, command: 36, law: 48 }, cycles: 54, certs: ["warden_mark"] },
        pay: 5900,
        unlocks: ["doctrine_pad", "armory_override"],
        next: "F",
      },
      {
        letter: "F",
        title: "Chief of Security",
        honorific: "Chief",
        duties:
          "A station's watch, a yard's guards, or a colony's militia. Politics wearing a uniform.",
        req: { skills: { command: 50, law: 52, security: 72 }, cycles: 76, certs: ["chief_writ"] },
        pay: 8000,
        unlocks: ["watch_budget", "militia_call"],
        next: "G",
      },
      {
        letter: "G",
        title: "Marshal of the Complex",
        honorific: "Marshal",
        duties:
          "The Security Complex. Charters, inter-habitat pursuit, and the right to close a dock.",
        req: { skills: { command: 68, law: 64, commerce: 20 }, cycles: 110, certs: ["complex_charter"] },
        pay: 10800,
        unlocks: ["complex_seal", "pursuit_writ", "dock_close"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "customs",
        name: "Customs & Claims",
        fromRank: "C",
        skills: { law: 30, supplyChain: 16, security: 30 },
        titleSuffix: "Customs",
        flavor: "Manifests, contraband, and miners who swear that crate was always empty.",
        unlocks: ["scan_bay", "seize_pad"],
      },
      {
        id: "boarding",
        name: "Boarding & Shipboard",
        fromRank: "C",
        skills: { security: 38, piloting: 16, firstAid: 16 },
        titleSuffix: "Boarding",
        flavor: "Hatches, zero-g fights, and the etiquette of not shooting the hull.",
        unlocks: ["cutter_team", "soft_breach"],
      },
      {
        id: "intel",
        name: "Internal Affairs & Intel",
        fromRank: "D",
        skills: { dataOps: 32, law: 40, psychiatry: 12 },
        titleSuffix: "Intel",
        flavor: "The people who watch the watch. Nobody likes you. That is the job.",
        unlocks: ["quiet_office", "tap_warrant"],
      },
    ],
  },

  navigation: {
    id: "navigation",
    name: "Navigation & Piloting Complex",
    short: "Conn",
    icon: "🧭",
    color: "#4a6fa5",
    setting:
      "Traffic control spheres, sim pits, and the chairs from which a bad plot kills two hundred sleepers. Space is empty until it is not.",
    primarySkills: ["navigation", "piloting", "dataOps"],
    related: ["logistics", "shipyard", "security", "energy"],
    ranks: [
      {
        letter: "A",
        title: "Traffic Cadet",
        honorific: "Cadet",
        duties:
          "Shadow a controller. Call distances. Learn the local debris and the captains who lie about mass.",
        req: { skills: { navigation: 8 }, cycles: 0, certs: ["cadet_conn"] },
        pay: 940,
        unlocks: ["scope_seat", "traffic_board"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Pilot",
        honorific: "Pilot",
        duties:
          "Tugs, shuttles, and supervised burns. Dock without kissing the clamp. Your first solo is a small room with a large audience.",
        req: { skills: { piloting: 18, navigation: 14 }, cycles: 5, certs: ["shuttle_ticket"] },
        pay: 1700,
        unlocks: ["shuttle_lease", "sim_hours"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Navigator",
        honorific: "Navigator",
        duties:
          "Plot a lane. Stand a conn watch. Take a freighter through a belt without becoming a story.",
        req: { skills: { navigation: 34, piloting: 30, dataOps: 16 }, cycles: 14, certs: ["conn_ticket"] },
        pay: 2700,
        unlocks: ["conn_watch", "lane_key"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Astrogator",
        honorific: "Astrogator",
        duties:
          "Deep plots, jump windows, and the math that keeps a liner off a gravity well. Teach cadets not to trust autopilot.",
        req: { skills: { navigation: 52, piloting: 44, dataOps: 28 }, cycles: 30, certs: ["astro_seal"] },
        pay: 4200,
        unlocks: ["deep_plot", "window_desk"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Helmsman",
        honorific: "Master Helmsman",
        duties:
          "Capitals, emergency undocks, and the night the traffic sphere went dark. Your hands are the last argument.",
        req: { skills: { piloting: 66, navigation: 62, command: 24 }, cycles: 54, certs: ["master_helm"] },
        pay: 6100,
        unlocks: ["capital_conn", "emergency_undock"],
        next: "F",
      },
      {
        letter: "F",
        title: "Harbor Master",
        honorific: "Harbor Master",
        duties:
          "A dock sphere or a system's lanes. Slots, fines, and the authority to hold a keel in the dark.",
        req: { skills: { command: 44, law: 24, navigation: 70 }, cycles: 76, certs: ["harbor_writ"] },
        pay: 8000,
        unlocks: ["slot_board", "hold_order"],
        next: "G",
      },
      {
        letter: "G",
        title: "Sky Marshal",
        honorific: "Sky Marshal",
        duties:
          "The Navigation Complex. Lanes, interdictions, and who may burn how close to a habitat.",
        req: { skills: { command: 64, law: 36, navigation: 78 }, cycles: 108, certs: ["complex_charter"] },
        pay: 10700,
        unlocks: ["complex_seal", "lane_charter", "interdict_flag"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "tug_dock",
        name: "Tug & Dockwork",
        fromRank: "B",
        skills: { piloting: 28, hullcraft: 8 },
        titleSuffix: "Tug",
        flavor: "The unglamorous art of putting a mountain into a clamp at walking speed.",
        unlocks: ["tug_lease", "clamp_override"],
      },
      {
        id: "deep_lane",
        name: "Deep Lane Astrogation",
        fromRank: "D",
        skills: { navigation: 55, dataOps: 30, research: 12 },
        titleSuffix: "Deep",
        flavor: "Charts that age. Ice that moves. The long dark between habitats.",
        unlocks: ["deep_charts", "probe_time"],
      },
      {
        id: "traffic_sphere",
        name: "Traffic Control",
        fromRank: "C",
        skills: { navigation: 36, dataOps: 28, command: 16 },
        titleSuffix: "Control",
        flavor: "A thousand moving knives. You talk. They live.",
        unlocks: ["sphere_chair", "priority_stack"],
      },
    ],
  },

  commerce: {
    id: "commerce",
    name: "Commerce & Trade Complex",
    short: "Exchange",
    icon: "💹",
    color: "#b8860b",
    setting:
      "Exchange floors, bonded warehouses, and contract rooms where a signature moves more mass than a tug. Credit is a kind of gravity.",
    primarySkills: ["commerce", "law", "supplyChain"],
    related: ["logistics", "manufacturing", "mining", "security"],
    ranks: [
      {
        letter: "A",
        title: "Floor Runner",
        honorific: "Runner",
        duties:
          "Carry tickets, watch boards, learn the hand signs. Survey a market before you bet a scrip.",
        req: { skills: { commerce: 8 }, cycles: 0, certs: ["floor_badge"] },
        pay: 860,
        unlocks: ["ticker_pad", "pit_pass"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Factor",
        honorific: "Factor",
        duties:
          "Small lots, posted prices, bonded storage. Make a market without making a mess.",
        req: { skills: { commerce: 18, supplyChain: 10 }, cycles: 4, certs: ["factor_card"] },
        pay: 1500,
        unlocks: ["lot_desk", "bond_locker"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Broker",
        honorific: "Broker",
        duties:
          "Match a miner to a yard. Write a contract that survives court. Keep a book that is not a fantasy.",
        req: { skills: { commerce: 34, law: 20, supplyChain: 20 }, cycles: 13, certs: ["broker_ticket"] },
        pay: 2550,
        unlocks: ["contract_desk", "court_standing"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Merchant",
        honorific: "Merchant",
        duties:
          "Own a book of routes and relationships. Hedge a famine. Finance a slip. People take your call.",
        req: { skills: { commerce: 50, law: 34, command: 16 }, cycles: 28, certs: ["merchant_seal"] },
        pay: 4000,
        unlocks: ["house_mark", "slip_finance"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Factor",
        honorific: "Master Factor",
        duties:
          "Set prices other people treat as weather. Train brokers. Sit on the exchange board.",
        req: { skills: { commerce: 66, law: 46, command: 28 }, cycles: 52, certs: ["master_factor"] },
        pay: 6000,
        unlocks: ["board_seat", "price_post"],
        next: "F",
      },
      {
        letter: "F",
        title: "House Principal",
        honorific: "Principal",
        duties:
          "A trading house: ships, warehouses, and the quiet wars over a commodity.",
        req: { skills: { command: 46, commerce: 74, law: 50 }, cycles: 74, certs: ["house_writ"] },
        pay: 8200,
        unlocks: ["house_charter", "warehouse_net"],
        next: "G",
      },
      {
        letter: "G",
        title: "Exchange Chancellor",
        honorific: "Chancellor",
        duties:
          "The Commerce Complex. Listings, halts, and the right to freeze a house.",
        req: { skills: { command: 66, law: 60, commerce: 80 }, cycles: 108, certs: ["complex_charter"] },
        pay: 11000,
        unlocks: ["complex_seal", "halt_order", "freeze_writ"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "commodities",
        name: "Ore & Commodity Books",
        fromRank: "C",
        skills: { commerce: 36, geology: 12, supplyChain: 24 },
        titleSuffix: "Commodities",
        flavor: "The rock becomes a number. The number becomes a war.",
        unlocks: ["ore_book", "future_desk"],
      },
      {
        id: "hull_finance",
        name: "Hull & Slip Finance",
        fromRank: "D",
        skills: { commerce: 50, hullcraft: 8, law: 30 },
        titleSuffix: "Hulls",
        flavor: "Ships are expensive. Someone has to own the debt.",
        unlocks: ["keel_bond", "insurance_desk"],
      },
      {
        id: "grey_market",
        name: "Gray Charter Trade",
        fromRank: "D",
        skills: { commerce: 48, law: 28, security: 16 },
        titleSuffix: "Gray",
        flavor: "Legal enough. Watched. Profitable. Do not ask the Marshal to toast you.",
        unlocks: ["gray_desk", "quiet_warehouse"],
      },
    ],
  },

  communications: {
    id: "communications",
    name: "Communications & Data Complex",
    short: "Comms",
    icon: "📡",
    color: "#5b8a9a",
    setting:
      "Arrays, relay buoys, server stacks in cold rooms, and the people who decide whose voice crosses a system first.",
    primarySkills: ["dataOps", "electronics", "law"],
    related: ["research", "navigation", "security", "commerce"],
    ranks: [
      {
        letter: "A",
        title: "Relay Aide",
        honorific: "Aide",
        duties:
          "Watch a board. Swap a card. Log dropouts. Survey the sky for a buoy that has gone mute.",
        req: { skills: { dataOps: 8 }, cycles: 0, certs: ["relay_badge"] },
        pay: 900,
        unlocks: ["board_seat", "card_kit"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Net Tech",
        honorific: "Net Tech",
        duties:
          "Keep a stack honest. Patch, backup, and explain to a captain why their movie cache is not priority traffic.",
        req: { skills: { dataOps: 18, electronics: 12 }, cycles: 4, certs: ["net_card"] },
        pay: 1480,
        unlocks: ["stack_keys", "patch_desk"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Operator",
        honorific: "Operator",
        duties:
          "Stand an array watch. Route a crisis channel. Lead two techs through a black-sky night.",
        req: { skills: { dataOps: 34, electronics: 24, navigation: 10 }, cycles: 13, certs: ["ops_ticket"] },
        pay: 2500,
        unlocks: ["array_watch", "crisis_channel"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Systems Architect",
        honorific: "Systems Architect",
        duties:
          "Design the net a habitat deserves. Encryption policy. Latency budgets. The quiet fight with Security over taps.",
        req: { skills: { dataOps: 50, electronics: 36, law: 20 }, cycles: 28, certs: ["arch_seal"] },
        pay: 3900,
        unlocks: ["net_design", "crypto_desk"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Signal Officer",
        honorific: "Master Signal",
        duties:
          "Qualify a new array. Teach operators. Decide which packets are sacred.",
        req: { skills: { dataOps: 66, command: 24, law: 28 }, cycles: 52, certs: ["master_signal"] },
        pay: 5700,
        unlocks: ["array_qualify", "sacred_list"],
        next: "F",
      },
      {
        letter: "F",
        title: "Array Chief",
        honorific: "Array Chief",
        duties:
          "A system's voice. Relays, stacks, and the politics of who is heard.",
        req: { skills: { command: 44, dataOps: 72, law: 32 }, cycles: 74, certs: ["chief_writ"] },
        pay: 7600,
        unlocks: ["relay_budget", "priority_stack"],
        next: "G",
      },
      {
        letter: "G",
        title: "Postmaster-General",
        honorific: "Postmaster-General",
        duties:
          "The Comms Complex. Ciphers, blackouts, and the right to silence a channel.",
        req: { skills: { command: 64, law: 44, dataOps: 78 }, cycles: 106, certs: ["complex_charter"] },
        pay: 10400,
        unlocks: ["complex_seal", "blackout_order", "cipher_charter"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "relay_ops",
        name: "Relay & Array Ops",
        fromRank: "C",
        skills: { dataOps: 36, electronics: 28, navigation: 16 },
        titleSuffix: "Array",
        flavor: "Hardware in the dark. Micrometeorites and politics both punch holes.",
        unlocks: ["buoy_tug", "dish_yard"],
      },
      {
        id: "crypto",
        name: "Cipher & Integrity",
        fromRank: "D",
        skills: { dataOps: 52, law: 24, research: 16 },
        titleSuffix: "Cipher",
        flavor: "Trust is a protocol. Break it and habitats start rumors.",
        unlocks: ["cipher_lab", "key_ceremony"],
      },
      {
        id: "newsnet",
        name: "Public Net & Record",
        fromRank: "C",
        skills: { dataOps: 30, law: 16, commerce: 12 },
        titleSuffix: "Record",
        flavor: "The official story, the unofficial story, and the archive that outlives both.",
        unlocks: ["record_desk", "bulletin_flag"],
      },
    ],
  },

  terraforming: {
    id: "terraforming",
    name: "Terraforming & Planetary Works Complex",
    short: "Worlds",
    icon: "🌍",
    color: "#3d7a5a",
    setting:
      "Century projects: mirrors, seed ships, atmosphere plants, and committees that argue about oceans they will not live to swim.",
    primarySkills: ["terraforming", "agriculture", "energySystems"],
    related: ["construction", "research", "agriculture", "mining"],
    ranks: [
      {
        letter: "A",
        title: "World Surveyor",
        honorific: "Surveyor",
        duties:
          "Walk a dead world. Core samples, wind roses, and the first honest map. Do not plant anything yet.",
        req: { skills: { terraforming: 8, geology: 8 }, cycles: 0, certs: ["world_badge"] },
        pay: 980,
        unlocks: ["core_kit", "world_map"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Works Tech",
        honorific: "Works Tech",
        duties:
          "Tend a mirror, a seed drone, or a gas plant. Learn that a planet is not a habitat with worse plumbing.",
        req: { skills: { terraforming: 18, energySystems: 10 }, cycles: 6, certs: ["works_card"] },
        pay: 1580,
        unlocks: ["seed_drone", "mirror_cart"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Planetary Tech",
        honorific: "Planetary Tech",
        duties:
          "Own a sector of a worksite. Track albedo. Fight a bloom that was not on the plan.",
        req: { skills: { terraforming: 34, agriculture: 20, energySystems: 18 }, cycles: 16, certs: ["sector_ticket"] },
        pay: 2650,
        unlocks: ["sector_keys", "albedo_desk"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient World Engineer",
        honorific: "World Engineer",
        duties:
          "Design a decade of work. Atmosphere budgets. Hydrology that will still be true when you are dust.",
        req: { skills: { terraforming: 52, agriculture: 34, research: 24 }, cycles: 36, certs: ["decade_seal"] },
        pay: 4200,
        unlocks: ["decade_plan", "hydro_model"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Planetary Engineer",
        honorific: "Master Engineer",
        duties:
          "Sign a world's phase gate. Teach engineers who will outlive you. Argue with Commerce about timelines.",
        req: { skills: { terraforming: 68, command: 28, law: 20 }, cycles: 60, certs: ["phase_mark"] },
        pay: 6200,
        unlocks: ["phase_gate", "teaching_seal"],
        next: "F",
      },
      {
        letter: "F",
        title: "Works Director",
        honorific: "Works Director",
        duties:
          "A planet's current phase. Mirrors, plants, politics, and the settlers who arrived early on purpose.",
        req: { skills: { command: 48, terraforming: 74, commerce: 24 }, cycles: 84, certs: ["director_writ"] },
        pay: 8400,
        unlocks: ["phase_budget", "settler_desk"],
        next: "G",
      },
      {
        letter: "G",
        title: "Worldwright",
        honorific: "Worldwright",
        duties:
          "The Terraforming Complex. Which worlds are opened, which are left sacred, and which mistakes become oceans.",
        req: { skills: { command: 68, law: 40, terraforming: 80 }, cycles: 120, certs: ["complex_charter"] },
        pay: 11200,
        unlocks: ["complex_seal", "open_world", "sacred_ban"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "atmo_works",
        name: "Atmosphere Works",
        fromRank: "C",
        skills: { terraforming: 36, energySystems: 24, research: 16 },
        titleSuffix: "Atmo",
        flavor: "Gas plants, algae blooms, and the long argument with a sky.",
        unlocks: ["gas_plant", "bloom_permit"],
      },
      {
        id: "insolation",
        name: "Insolation & Mirrors",
        fromRank: "C",
        skills: { terraforming: 34, navigation: 16, energySystems: 24 },
        titleSuffix: "Mirrors",
        flavor: "Steal sunlight. Aim it. Do not cook a city.",
        unlocks: ["mirror_farm", "aim_desk"],
      },
      {
        id: "biosphere",
        name: "Biosphere Seeding",
        fromRank: "D",
        skills: { agriculture: 40, genetics: 28, terraforming: 50 },
        titleSuffix: "Seed",
        flavor: "Introduce a web of life that will not eat the settlers.",
        unlocks: ["seed_ship", "web_model"],
      },
    ],
  },

  salvage: {
    id: "salvage",
    name: "Salvage & Reclamation Complex",
    short: "Wrecks",
    icon: "♻️",
    color: "#7a6a58",
    setting:
      "Bone yards, derelicts, and the legal gray of who owned a hull yesterday. One bad cut vents a fortune. One good cut funds a life.",
    primarySkills: ["salvage", "hullcraft", "law"],
    related: ["mining", "shipyard", "manufacturing", "security"],
    ranks: [
      {
        letter: "A",
        title: "Wreck Surveyor",
        honorific: "Surveyor",
        duties:
          "Tag a hulk. Scan for live power, live air, live claims. Do not cut until the law is clear.",
        req: { skills: { salvage: 8, law: 6 }, cycles: 0, certs: ["wreck_badge"] },
        pay: 920,
        unlocks: ["tag_kit", "live_scan"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Cutter",
        honorific: "Cutter",
        duties:
          "Cut under a journeyman. Bag plate. Learn which tanks still hold spite.",
        req: { skills: { salvage: 18, hullcraft: 12, hazardOps: 10 }, cycles: 5, certs: ["cut_card"] },
        pay: 1520,
        unlocks: ["cutter_rig", "spite_meter"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Reclaimer",
        honorific: "Reclaimer",
        duties:
          "Own a section of a wreck. File a lawful yield. Lead two cutters through a dark hull.",
        req: { skills: { salvage: 34, hullcraft: 24, law: 16 }, cycles: 14, certs: ["section_ticket"] },
        pay: 2500,
        unlocks: ["section_claim", "yield_desk"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Wrecker",
        honorific: "Wrecker",
        duties:
          "Take a whole small hull. Negotiate with heirs and navies. Know what is scrap and what is evidence.",
        req: { skills: { salvage: 50, law: 32, hullcraft: 36 }, cycles: 30, certs: ["wreck_seal"] },
        pay: 3900,
        unlocks: ["small_hull_rights", "evidence_hold"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master Reclaimer",
        honorific: "Master Reclaimer",
        duties:
          "Capitals, war graves, and the jobs that need a chaplain on site. Train wreckers. Sign the quiet reports.",
        req: { skills: { salvage: 66, law: 44, command: 24 }, cycles: 54, certs: ["master_wreck"] },
        pay: 5800,
        unlocks: ["capital_rights", "grave_protocol"],
        next: "F",
      },
      {
        letter: "F",
        title: "Yard Boss",
        honorific: "Yard Boss",
        duties:
          "A bone yard. What is stripped, what is rebuilt, what is left as a warning.",
        req: { skills: { command: 44, salvage: 72, commerce: 24 }, cycles: 76, certs: ["boss_writ"] },
        pay: 7700,
        unlocks: ["yard_charter", "rebuild_line"],
        next: "G",
      },
      {
        letter: "G",
        title: "Reclamation Marshal",
        honorific: "Marshal",
        duties:
          "The Salvage Complex. Prize courts, war-grave bans, and the right to condemn a hulk.",
        req: { skills: { command: 64, law: 56, salvage: 78 }, cycles: 108, certs: ["complex_charter"] },
        pay: 10500,
        unlocks: ["complex_seal", "prize_court", "condemn_hulk"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "live_wreck",
        name: "Live-Power Wrecks",
        fromRank: "C",
        skills: { salvage: 36, energySystems: 20, hazardOps: 28 },
        titleSuffix: "Hot",
        flavor: "The lights are still on. That is not comfort.",
        unlocks: ["hot_rig", "scram_cut"],
      },
      {
        id: "prize_law",
        name: "Prize & Claims Law",
        fromRank: "D",
        skills: { law: 40, commerce: 20, salvage: 44 },
        titleSuffix: "Prize",
        flavor: "The cut is easy. The paperwork is the real vacuum.",
        unlocks: ["prize_desk", "heir_search"],
      },
      {
        id: "rebuild",
        name: "Rebuild & Refit",
        fromRank: "D",
        skills: { hullcraft: 40, salvage: 44, precisionFab: 16 },
        titleSuffix: "Rebuild",
        flavor: "Not all hulks want to die. Some want a second name.",
        unlocks: ["rebuild_slip", "rename_plate"],
      },
    ],
  },

  education: {
    id: "education",
    name: "Education & Guild Complex",
    short: "Guilds",
    icon: "📚",
    color: "#6b5b8a",
    setting:
      "Apprentice halls, sim pits, and the ticket offices that decide whether a child becomes a miner or a marshal. Civilization is a curriculum.",
    primarySkills: ["command", "research", "law"],
    related: ["research", "healthcare", "security", "navigation"],
    ranks: [
      {
        letter: "A",
        title: "Hall Aide",
        honorific: "Aide",
        duties:
          "Keep the sim pits honest. Fetch texts. Watch apprentices so they do not weld themselves to the floor.",
        req: { skills: { command: 6, research: 6 }, cycles: 0, certs: ["hall_badge"] },
        pay: 840,
        unlocks: ["pit_keys", "text_pad"],
        next: "B",
      },
      {
        letter: "B",
        title: "Entry Instructor",
        honorific: "Instructor",
        duties:
          "Teach a module you have already lived. Grade without cruelty or kindness. Issue the first stamps.",
        req: { skills: { command: 16, research: 14 }, cycles: 8, certs: ["instruct_card"] },
        pay: 1550,
        unlocks: ["module_desk", "stamp_press"],
        next: "C",
      },
      {
        letter: "C",
        title: "Journeyman Preceptor",
        honorific: "Preceptor",
        duties:
          "Own a course. Design a test that measures the job, not the lecture. Mentor two instructors.",
        req: { skills: { command: 30, research: 26, law: 12 }, cycles: 18, certs: ["course_ticket"] },
        pay: 2500,
        unlocks: ["course_charter", "exam_board"],
        next: "D",
        specializationUnlock: true,
      },
      {
        letter: "D",
        title: "Proficient Guild Lecturer",
        honorific: "Lecturer",
        duties:
          "Cross-complex curriculum. Argue with Foremen about what a ticket should mean. Publish a manual that yards actually use.",
        req: { skills: { command: 44, research: 40, law: 24 }, cycles: 34, certs: ["lecturer_seal"] },
        pay: 3800,
        unlocks: ["manual_press", "cross_ticket"],
        next: "E",
      },
      {
        letter: "E",
        title: "Master of Apprentices",
        honorific: "Master of Apprentices",
        duties:
          "The pipeline. Who is ready, who is not, and which complexes are starving for hands.",
        req: { skills: { command: 58, law: 32, commerce: 16 }, cycles: 56, certs: ["master_hall"] },
        pay: 5600,
        unlocks: ["pipeline_desk", "placement_seal"],
        next: "F",
      },
      {
        letter: "F",
        title: "Dean of Guilds",
        honorific: "Dean",
        duties:
          "A hall or a system's tickets. Standards, appeals, and the quiet sale of seats.",
        req: { skills: { command: 64, law: 44, research: 40 }, cycles: 78, certs: ["dean_writ"] },
        pay: 7500,
        unlocks: ["appeals_board", "seat_charter"],
        next: "G",
      },
      {
        letter: "G",
        title: "Chancellor of Tickets",
        honorific: "Chancellor",
        duties:
          "The Education Complex. Which tickets exist, which are forged, and which worlds get a hall.",
        req: { skills: { command: 74, law: 56, commerce: 28 }, cycles: 112, certs: ["complex_charter"] },
        pay: 10200,
        unlocks: ["complex_seal", "ticket_charter", "forge_ban"],
        next: null,
      },
    ],
    specializations: [
      {
        id: "sim_pits",
        name: "Simulation & Drill",
        fromRank: "C",
        skills: { command: 28, dataOps: 16, piloting: 8 },
        titleSuffix: "Sims",
        flavor: "Break them in the pit so the void does not.",
        unlocks: ["pit_director", "scenario_desk"],
      },
      {
        id: "ticket_law",
        name: "Certification Law",
        fromRank: "D",
        skills: { law: 36, command: 36 },
        titleSuffix: "Tickets",
        flavor: "A stamp is a weapon. Treat it that way.",
        unlocks: ["forensics_stamp", "revoke_desk"],
      },
      {
        id: "field_precept",
        name: "Field Preceptorship",
        fromRank: "C",
        skills: { command: 30, hazardOps: 12 },
        titleSuffix: "Field",
        flavor: "Teach on the cut, the slip, the ward. The hall is a rumor out here.",
        unlocks: ["field_hall", "ride_along"],
      },
    ],
  },
};

export const COMPLEX_IDS = Object.keys(COMPLEXES);

export function getComplex(id) {
  return COMPLEXES[id] || null;
}

export function getRank(complexId, letter) {
  const c = getComplex(complexId);
  if (!c) return null;
  return c.ranks.find((r) => r.letter === letter) || null;
}

export function getSpecialization(complexId, specId) {
  const c = getComplex(complexId);
  if (!c) return null;
  return c.specializations.find((s) => s.id === specId) || null;
}
