// Living Galaxy — tuning: hulls, prices, fitting budgets, interlocks and module wear.
//
// One of twelve files under `core/config/`. `config.js` was a single 1,727-line module and
// the most-imported file in the project, which made it the place every tuning value went and
// no place in particular — a new block landed wherever the last one ended.
//
// The split mirrors `src/systems/`: a number that tunes `systems/combat/` lives in
// `config/combat.js`. `core/config.js` re-exports all twelve, so every existing import is
// untouched and a caller that wants one domain can reach for it directly.
//
// Pure data. No imports, no behaviour.

// ── hulls ────────────────────────────────────────────────────────────
// maxSpeed / warpSpeed are units per second. cargoCap is kg.
export const SHIP_CLASSES = {
  military:   {name:'Military',   icon:'⚔', heatCap:130, dryMass:8500,  maxThrust:2.8e6, cargoCap:1200,  turnRate:1.40, pitchRate:1.20,
               energyCap:100, energyDrainThrust:18, energyDrainTurn:4.0, energyRegen:7.0,
               shieldMax:120, shieldRegen:5.5, armorMax:90,  hullMax:100, maxSpeed:2.9, warpSpeed:1500,
               weapon:'gauss',   weaponMult:1.30, miningMult:0.45, sensor:4600},
  industrial: {name:'Industrial', icon:'⚙', heatCap:95, dryMass:18500, maxThrust:3.2e6, cargoCap:18000, turnRate:0.70, pitchRate:0.65,
               energyCap:140, energyDrainThrust:22, energyDrainTurn:6.0, energyRegen:9.0,
               shieldMax:80,  shieldRegen:3.0, armorMax:140, hullMax:130, maxSpeed:2.1, warpSpeed:1100,
               weapon:'scatter', weaponMult:0.80, miningMult:1.60, sensor:5200},
  logistics:  {name:'Logistics',  icon:'📦', heatCap:100, dryMass:14000, maxThrust:2.6e6, cargoCap:22000, turnRate:0.85, pitchRate:0.80,
               energyCap:120, energyDrainThrust:16, energyDrainTurn:5.0, energyRegen:8.0,
               shieldMax:90,  shieldRegen:4.0, armorMax:110, hullMax:110, maxSpeed:2.4, warpSpeed:1800,
               weapon:'pulse',   weaponMult:0.90, miningMult:0.85, sensor:4800},
  economic:   {name:'Economic',   icon:'💰', heatCap:105, dryMass:9500,  maxThrust:2.4e6, cargoCap:6000,  turnRate:1.10, pitchRate:1.05,
               energyCap:110, energyDrainThrust:14, energyDrainTurn:3.5, energyRegen:8.5,
               shieldMax:100, shieldRegen:4.5, armorMax:85,  hullMax:95,  maxSpeed:2.6, warpSpeed:1400,
               weapon:'pulse',   weaponMult:1.00, miningMult:0.70, sensor:5000},
  civilian:   {name:'Civilian',   icon:'🛰', heatCap:80, dryMass:7200,  maxThrust:1.6e6, cargoCap:2500,  turnRate:1.15, pitchRate:1.10,
               energyCap:90,  energyDrainThrust:11, energyDrainTurn:3.0, energyRegen:6.5,
               shieldMax:70,  shieldRegen:4.0, armorMax:70,  hullMax:85,  maxSpeed:2.5, warpSpeed:1300,
               weapon:'scatter', weaponMult:0.70, miningMult:0.60, sensor:4200}
};
export const CLASS_ORDER = ['military','industrial','logistics','economic','civilian'];

// You start in a civilian hull. Every other career path is a hull you must BUY at a
// shipyard (any station's Refit tab). Owned hulls can be swapped between for free.
// Hull prices tripled in the 1.0 pass. Together with the commodity cut they put a hull
// at roughly one good haul rather than a fraction of one: an 18-tonne industrial run is
// about 70,000 credits and a military hull with its licence is about 73,000. Before the
// pass a single load bought every ship in the game twice over, which is why none of the
// tiers below meant anything.
export const SHIP_PRICE = {
  civilian: 0, economic: 12600, logistics: 20400, industrial: 28500, military: 42000
};
export const START_CLASS = 'civilian';

// ── fitting budgets ──────────────────────────────────────────────────
// Until 0.7 a fit was a shopping list: the only limit was the number of hardpoints and
// whether you could afford the parts, so the optimal fit was "the most expensive thing
// that fits in each slot" and there was no decision in it. Two budgets fix that.
//
//   Power  is generated by the hull and drawn by every fitted module.
//   CPU    is bandwidth, not energy — how much the flight computer can actually run.
//
// Going over either does not simply stop you. It degrades, progressively, so an
// over-tight fit is a gamble rather than an error message.
export const BUDGET = {
  // Tuned against the heaviest *legal* fit — every hardpoint filled with the hungriest
  // module that fits it, which for the current table is 7.0 MW and 24.3 tf. A big hull
  // carries that comfortably; a civilian shuttle is about 20% over on both and has to
  // choose. A budget the game cannot exceed is decoration, which is precisely the
  // criticism this system exists to answer.
  powerPerHull: { military: 7.4, industrial: 9.0, logistics: 8.0, economic: 7.6, civilian: 5.8 },
  cpuPerHull: { military: 26, industrial: 30, logistics: 28, economic: 27, civilian: 20 },
  cpuPerRank: 1.6,        // Engineering rank raises what you can run
  powerPerRank: 0.9,      // ...and what you can feed
  overloadGrace: 0.05,    // 5% over is free — floating-point slack, not a build strategy
  // Past the grace, every 10% of overload costs this much of the offending resource's
  // dependent systems.
  powerPenalty: 0.55,     // shield regen, energy recharge
  cpuPenalty: 0.45,       // sensors, scan rate, tracking
  maxPenalty: 0.75        // never fully disable a ship — a soft-lock is not a tradeoff
};

// ── fitting ──────────────────────────────────────────────────────────
// Every hull has three kinds of hardpoint. Weapon slots take guns/launchers,
// utility slots take active kit, core slots take permanent subsystems.
// Refits (UPGRADES above) still apply on top — slots are about *arrangement*.
export const HULL_SLOTS = {
  military:   { weapon: 3, utility: 2, core: 2 },
  industrial: { weapon: 1, utility: 3, core: 3 },
  logistics:  { weapon: 1, utility: 4, core: 2 },
  economic:   { weapon: 2, utility: 3, core: 2 },
  civilian:   { weapon: 1, utility: 2, core: 2 }
};
// Firing every mounted gun at once would trivialise a 3-slot military hull, so
// each extra barrel past the first contributes at a falloff.
export const MULTI_GUN_FALLOFF = 0.78;

// ── interlocks ───────────────────────────────────────────────────────
// The numbers behind systems/preflight.js. Kept here rather than inline so a hull that
// locks its cutter out too eagerly is a tuning change, not a code change.
export const INTERLOCK = {
  repeat: 1.4,               // s before the same refusal is spoken again
  cutterHullFloor: 0.18,     // fraction of hull below which the cutter arm will not run
  cutterEnergyMargin: 2.0,   // multiples of the per-second draw needed to strike an arc
  warpEnergy: 25             // matches the old inline constant in warp.js
};

// ── module wear (v1.01.70) ───────────────────────────────────────────
// The third item deferred out of v1.00.20, and the last one. Ammunition and heat landed in
// v1.00.60; condition never did.
//
// The design constraint, and the reason this is not a clock: **wear must be a consequence of
// what you did, not a tax on having played.** A module that degrades on a timer is rent —
// you pay it whether you fought or docked, and the only decision it creates is a chore. So
// every channel below is an event the pilot chose: a shot fired, a hit taken, a cruise
// flown, a beam held on a rock.
//
// The effect reuses the budget system rather than inventing a second penalty. A worn module
// gives less *and* draws more, which pushes a fit that was comfortable toward the overload
// curve v0.7 already built. A pilot who has been ignoring maintenance does not get a new
// error message; they find their existing one arriving sooner.
export const WEAR = {
  // Condition runs 1 (yard-fresh) down to 0 (worn out). Nothing is ever destroyed — a dead
  // module is a soft-lock at the worst possible moment, and "degrade rather than refuse" is
  // the rule the fitting budgets already follow.
  floor: 0.55,            // effectiveness of a module at zero condition
  drawAtZero: 0.35,       // extra power/CPU draw at zero condition, as a fraction

  // Per-channel rates, all per event rather than per second unless stated.
  //
  // These are the second set. The first was written by feel and measured afterwards, and it
  // was wrong by roughly an order of magnitude in every channel: 24 seconds of continuous
  // fire to reach the warning threshold, 2.2 minutes of mining, 2.7 minutes of cruise. That
  // is not wear, it is a chore on a two-minute timer — and it fails the test this whole
  // block is written against, because a bill that arrives every few minutes is rent whether
  // or not the clock driving it is called an event.
  //
  // Calibrated instead against a *session*: roughly half an hour of doing the thing before
  // the fitting screen says anything, and about an hour before it is worth a detour. The
  // figures below are what a measurement script reports, not what they look like.
  perShot: 0.00025,       // per round out of a barrel, on that hardpoint only
  perHullHit: 0.0012,     // per hit that reaches structure, spread across core and utility
  perArmorHit: 0.00035,   // armour absorbs; it is gentler on the ship's systems
  perWarpSecond: 0.00015, // core subsystems, while actually cruising
  // Mining is gentler per second than anything else here, because it is the only channel a
  // pilot runs *continuously* — a fight is seconds of trigger inside minutes of manoeuvre,
  // and a cruise ends when you arrive, but a belt session is an unbroken half hour of beam.
  // At the same rate as the others it was warning after two hold-fills.
  perMineSecond: 0.00009, // utility, while the beam is on a rock

  // Heat multiplies everything. Running a rack at the cutout is how a gun gets destroyed in
  // every navy that has ever had one, and it gives the thermal budget a second consequence
  // beyond the tempo one v1.00.60 built.
  heatMult: 1.9,          // at full heat; scales linearly from 1 at cold
  // An engineer on watch slows it. This is the crew tie-in that makes the speciality worth
  // posting outside a fight.
  engineerRelief: 0.35,   // fraction of wear an on-watch engineer prevents

  // Servicing, at a station. Priced against the module's own value so a cheap module is
  // cheap to keep and a capital-grade core is a commitment.
  serviceFraction: 0.22,  // of list price, to take a module from 0 to 1
  serviceMin: 45,         // nobody opens a panel for less
  // Below this the fitting screen says so and preflight mentions it once. Above it, wear is
  // real and invisible, which is correct: a 3% loss is not news.
  warnAt: 0.72,
  badAt: 0.40
};
